spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobboard
    username: postgres
    password: Faijan
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: INFO
    com.xcelerateit: DEBUG